# Having this as a separate workflow keeps the build.yml workflow fast, for a
# shorter iteration cycle.
name: coverage

on: [push, pull_request]

jobs:
  test:
    name: JDK ${{matrix.java}}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Run mutation test
      run: ./gradlew pitest

    - name: Make Coveralls report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.github_token }}
      run: ./gradlew coveralls

    - name: Upload Coveralls report
      # // Workaround to TLS issues in JDK 11, see https://github.com/kt3k/coveralls-gradle-plugin/issues/85
      run: curl -F 'json_file=@build/coveralls/report.json' https://coveralls.io/api/v1/jobs
