# Having this as a separate workflow keeps the build.yml workflow fast, for a
# shorter iteration cycle.
name: coverage

on: [push, pull_request]

jobs:
  test:
    name: JDK ${{matrix.java}}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Run mutation test
      run: ./gradlew pitest

    - name: Upload coverage report to Coveralls
      run: ./gradlew coveralls
